cifcesar:	funcoes.o cifra.o
	gcc -Wall funcoes.o cifra.o -o cifcesar

test.o: test.c
	gcc -c -Wall test.c -o test.o

funcoes.o: funcoes.c
	gcc -c -Wall funcoes.c -o funcoes.o

cifra.o: cifra.c
	gcc -c -Wall cifra.c -o cifra.o