letra:	funcoes.o letra.o
	gcc -Wall funcoes.o letra.o -o letra

letexto:	funcoes.o letexto.o
	gcc -Wall funcoes.o letexto.o -o letexto

funcoes.o:	funcoes.c
	gcc -c -Wall funcoes.c -o funcoes.o

letra.o: letra.c
	gcc -c -Wall letra.c -o letra.o

letexto.o: letexto.c
	gcc -c -Wall letexto.c -o letexto.o
	